version: '3'
services:
  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./service/orderdb:/docker-entrypoint-initdb.d